[package]
name = "parallel_untar"
authors = ["feng liang <feng.liang@kaust.edu.sa>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
glob = "0.3"
clap = "3.0.0-beta.2"